### ISSUE TITLE
Docker: elasticsearch.hosts must allow an array of endpoints

### ISSUE THREAD

**Issue by canasdiaz** [grimoirelab/kibiter#141]
The bug below affects the docker image: **bitergia/kibiter:secured-v6.8.6-1**

Kibana 6.8.6 uses a new parameter to declare the endpoints where the ES cluster is bind. This is named `elasticsearch.hosts`. The Docker container is using the same variable we used in 6.1 to map an endpoint to that new parameter. This is nice because we don't need to think about the new variables but it is not correctly done. One of the goodies of this new parameter is that is allows an array of nodes.

The env variable available for Kibana 6.8.6 is the one below, have a look at the array.
```
ELASTICSEARCH_HOSTS='["http://10.45.3.2:9220","http://10.45.3.1:9230"]'
```
In our code we are just waiting for a single endpoint, which is reducing the new features provided by Kibana and affecting some of the customer of Bitergia as we need to use it.

https://github.com/chaoss/grimoirelab-kibiter/blob/integration-community-6.8.6/docker/docker_entrypoint.sh#L14

**Comment by canasdiaz** [comment]
Just in case we want to copy they way this is done by the Elastic folks.

They use the following env variable in the container:
```
    kibana:
      image: docker.elastic.co/kibana/kibana-oss:6.8.6
      environment:
        - ELASTICSEARCH_USERNAME=kibanaserver
        - ELASTICSEARCH_PASSWORD=kibanaserver
        - ELASTICSEARCH_HOSTS=["https://elasticsearch1:9200","https://elasticsearch2:9100"]
        - ELASTICSEARCH_SSL_VERIFICATIONMODE=none
      ports:
        - 5602:5601
```

And this is the execution call they produce for that variable:
```
/usr/share/kibana/bin/../node/bin/node --no-warnings --max-http-header-size=65536 /usr/share/kibana/bin/../src/cli --cpu.cgroup.path.override=/ --cpuacct.cgroup.path.override=/ --elasticsearch.hosts=["https://elasticsearch1:9200","https://elasticsearch2:9100"] --elasticsearch.password=kibanaserver --elasticsearch.ssl.verificationMode=none --elasticsearch.username=kibanaserver
```
